---
title: "Tutorial 1"
author: "Gareth Steinmann (23627271)"
date: "2023-07-28"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

##Question 1.1.

```{r}
data = read.csv("C:/Users/Gerett/Documents/University/2nd Year/Stats 244/Chapter 1/Data Sets/FUNDS2002.csv", header = TRUE)
head(data)

lrg_cap = data[data$Type == "large cap ",]
lrg_cap
set.seed(5127)
sample_numbers_l = sample(1:nrow(lrg_cap), 15, replace = FALSE)
sort(sample_numbers_l)
l_sample = lrg_cap[sample_numbers_l,]
l_sample
```

##Question 1.2.

```{r}
mid_cap = data[data$Type == "mid cap",]
mid_cap
set.seed(2340)
sample_numbers_m = sample(1:nrow(mid_cap), 15, replace = FALSE)
sort(sample_numbers_m)
m_sample = mid_cap[sample_numbers_m,]
m_sample
```

##Question 1.3.

```{r}
sml_cap = data[data$Type == "small cap ",]
sml_cap
set.seed(2340)
sample_numbers_s = sample(1:nrow(sml_cap), 15, replace = FALSE)
sort(sample_numbers_s)
s_sample = sml_cap[sample_numbers_s,]
s_sample
```

##Question 2.1.

```{r}
N = as.integer(length(data$Type))
k1 = 7
set.seed(1326)
start1 = ceiling(runif(1,0,1)*k1)
start1

sample1 = seq.int(from = start1, to = N, by = k1)
sample1
head(sample1)
```

##Question 2.2.
```{r}
n2 = 20
k2 = ceiling(N/n2)
set.seed(2547)
start2 = ceiling(runif(1,0,1)*k2)
start2

sample2 = seq.int(from = start2, to = N, by = k2)
sample2
head(sample2)
```

##Question 2.3.
```{r}
n3 = ceiling(N*0.09)
k3 = ceiling(N/n3)
set.seed(2146)
start3 = ceiling(runif(1,0,1)*k3)
start3

sample3 = seq.int(from = start3, to = N, by = k3)
sample3
head(sample3)
```

##Question 2.4.
```{r}
data_sample1 = data[sample1,]
data_sample1
mean_data_sample_1 = mean(data_sample1$Assets)
mean_data_sample_1

data_sample2 = data[sample2,]
data_sample2
mean_data_sample_2 = mean(data_sample2$Assets)
mean_data_sample_2

data_sample3 = data[sample3,]
data_sample3
mean_data_sample_3 = mean(data_sample3$Assets)
mean_data_sample_3
```

##Question 3
```{r}
invoices = read.csv("C:/Users/Gerett/Documents/University/2nd Year/Stats 244/Chapter 1/Data Sets/INVOICES.csv", header = TRUE)
invoices
inv_num = (invoices$InvoiceNumber)
inv_num
inv_amount = (invoices$InvoiceAmount)
inv_amount

set.seed(5421)
probsize = inv_amount/sum(inv_amount)
probsize
inv_sample = sample(inv_num, 7, replace = FALSE, prob = probsize)
inv_sample

chosen_invoices = invoices[inv_sample,]
chosen_invoices
```

##Question 4
```{r}
stocks = read.table("C:/Users/Gerett/Documents/University/2nd Year/Stats 244/Chapter 1/Data Sets/STOCKSLOG.txt", header = TRUE)
head(stocks)

set.seed(125468)
mean = mean(stocks$Price)
mean
variance = var(stocks$Price)
variance
alpha = 3
beta = 1.1


ggplot (stocks, aes (sample = Price)) +
geom_qq(distribution = qnorm) +
geom_qq_line (distribution = qnorm)

ggplot (stocks, aes (sample = Price)) +
geom_qq(distribution = qlnorm) +
geom_qq_line (distribution = qlnorm)
```
